spring.application.name=backend-streaming
server.port=8080

spring.profiles.default=dev

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false
spring.jackson.default-property-inclusion=non_null

app.cors.allowed-origins=http://localhost:5173
app.oauth2.authorized-redirect-uri=http://localhost:5173/oauth-success

# Stripe
app.billing.currency=PEN
app.stripe.publishable-key=
app.stripe.secret-key=
app.stripe.webhook-secret=

jwt.expiration=86400000
jwt.refresh-expiration=604800000

spring.security.oauth2.client.registration.google.scope=email,profile
