spring.datasource.url=jdbc:mysql://localhost:3306/streaming_db1
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=95814595123456753478554567876542

# GOOGLE OAUTH2
spring.security.oauth2.client.registration.google.client-id=905630454023-a5g7pt2odjmp6am133997tp5pa5gguqh.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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